apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-deployment
  labels:
    app: hello
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: hossin91/k8s-web-server:1.2
        ports:
        - containerPort: 3000
